CREATE TABLE PRODUCT (
    PID INT,
    PNAME VARCHAR(40),
    IMG LONGBLOB,
    PRICE VARCHAR(40),
    USERNAME CHAR(10),
    OTHER VARCHAR(1000),
    PRIMARY KEY (PID),
    FOREIGN KEY (USERNAME) REFERENCES login(USERNAME) 
    ON DELETE CASCADE
);

CREATE TABLE PRODUCT_PICTURE (
    ID INT AUTO_INCREMENT,
    PRODUCTID INT,
    IMG LONGBLOB,
    PRIMARY KEY(ID),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PID) 
    ON DELETE CASCADE
);

