DELETE FROM PRODUCT;

INSERT INTO PRODUCT (PID, PNAME, IMG, PRICE, USERNAME, OTHER)
VALUES (1, "DD", "../public/images/pts.jpg", 10000, "khanh123", "OTHER");

INSERT INTO PRODUCT (PID, PNAME, IMG, PRICE, USERNAME, OTHER)
VALUES (2, "DaaD", "../public/images/pts.jpg", 10000,"khanh123", "OTHER");

INSERT INTO PRODUCT (PID, PNAME, IMG, PRICE, USERNAME, OTHER)
VALUES (3, "DddD", "../public/images/pts.jpg", 10000,"khanh123", "OTHER");

INSERT INTO PRODUCT (PID, PNAME, IMG, PRICE, USERNAME, OTHER)
VALUES (4, "DcsD", "../public/images/pts.jpg", 10000,"khanh123", "OTHER");

INSERT INTO PRODUCT (PID, PNAME, IMG, PRICE, USERNAME, OTHER)
VALUES (5, "DdsaD", "../public/images/pts.jpg", 10000,"khanh123", "OTHER");

INSERT INTO PRODUCT (PID, PNAME, IMG, PRICE, USERNAME, OTHER)
VALUES (6, "DdsaD", "../public/images/pts.jpg", 10000,"khanh1e2", "OTHER");

INSERT INTO PRODUCT (PID, PNAME, IMG, PRICE, USERNAME, OTHER)
VALUES (7, "DdsaD", "../public/images/pts.jpg", 10000,"khanh1e2", "OTHER");

INSERT INTO PRODUCT (PID, PNAME, IMG, PRICE, USERNAME, OTHER)
VALUES (8, "DewqD", "../public/images/pts.jpg", 10000,"khanh1e2", "OTHER");

INSERT INTO PRODUCT (PID, PNAME, IMG, PRICE, USERNAME, OTHER)
VALUES (9, "DewqD", "../public/images/pts.jpg", 10000,"khanh1e2", "OTHER");

INSERT INTO PRODUCT (PID, PNAME, IMG, PRICE, USERNAME, OTHER)
VALUES (10, "DewqD", "../public/images/pts.jpg", 10000,"khanh1e2", "OTHER");